# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

check_update:
  stage: build
  script:
  - ./config --strict-warnings
  - make -s update
  - git diff --exit-code

basic_gcc  
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - ./config --strict-warnings
    - make -s -j4
    - make test
  
