language: c
cache: ccache

addons:
    apt:
        packages:
            - ccache
            - clang-3.6
            - gcc-5
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test

os:
    - linux
    - osx

compiler:
    - clang
    - clang-3.6
    - gcc
    - gcc-5

env:
    - CONFIG_OPTS=""
    - CONFIG_OPTS="shared"
    - CONFIG_OPTS="no-pic"
    - CONFIG_OPTS="--debug --strict-warnings enable-crypto-mdebug enable-rc5 enable-md2"
    - CONFIG_OPTS="--unified" BUILDDIR=_build-plain BUILDONLY="yes"
    - CONFIG_OPTS="--unified shared" BUILDDIR=_build-shared BUILDONLY="yes"
    - CONFIG_OPTS="--unified --debug --strict-warnings enable-rc5 enable-md2" BUILDDIR=_build-debug BUILDONLY="yes"

matrix:
    include:
        - os: linux
          compiler: clang-3.6
          env: CONFIG_OPTS="-fsanitize=address"
        - os: linux
          compiler: clang-3.6
          env: CONFIG_OPTS="no-asm --strict-warnings -fno-sanitize-recover -fsanitize=address -fsanitize=undefined enable-rc5 enable-md2"
        - os: linux
          compiler: gcc-5
          env: CONFIG_OPTS="-fsanitize=address"
        - os: linux
          compiler: gcc-5
          env: CONFIG_OPTS="no-asm --strict-warnings -fno-sanitize-recover -fsanitize=address -fsanitize=undefined enable-rc5 enable-md2"
        - os: linux
          compiler: clang
          env: CONFIG_OPTS="no-engine" BUILDONLY="yes"
    exclude:
        - os: osx
          compiler: clang-3.6
        - os: osx
          compiler: gcc
        - os: osx
          compiler: gcc-5

before_script:
    - sh .travis-create-release.sh $TRAVIS_OS_NAME
    - tar -xvzf _srcdist.tar.gz
    - if [ -n "$BUILDDIR" ]; then
          srcdir=../_srcdist;
          mkdir $BUILDDIR;
          cd $BUILDDIR;
          if which ccache >/dev/null; then
              CC="ccache $CC";
          fi
      else
          srcdir=.;
          cd _srcdist;
      fi
    - if [ "$CC" == i686-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          $srcdir/Configure mingw $CONFIG_OPTS -Wno-pedantic-ms-format;
      elif [ "$CC" == x86_64-w64-mingw32-gcc ]; then
          export CROSS_COMPILE=${CC%%gcc}; unset CC;
          $srcdir/Configure mingw64 $CONFIG_OPTS -Wno-pedantic-ms-format;
      else
          $srcdir/config $CONFIG_OPTS;
      fi
    - cd ..

script:
    - if [ -n "$BUILDDIR" ]; then
          cd $BUILDDIR;
      else
          cd _srcdist;
      fi
    - make
    - if [ -z "$BUILDONLY" ]; then
          HARNESS_VERBOSE=yes make test;
      fi
    - cd ..

notifications:
    email:
        - openssl-commits@openssl.org

