language: c

addons:
    apt:
        packages:
            - clang-3.6
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test

os:
    - osx

compiler:
    - clang

env:
    - CONFIG_OPTS=""
    - CONFIG_OPTS="shared"
    - CONFIG_OPTS="no-asm"
    - CONFIG_OPTS="--debug --strict-warnings enable-crypto-mdebug enable-rc5 enable-md2"
    - CONFIG_OPTS="--unified"
    - CONFIG_OPTS="--unified shared"
    - CONFIG_OPTS="--unified no-asm"
    - CONFIG_OPTS="--unified --debug --strict-warnings enable-crypto-mdebug enable-rc5 enable-md2"

before_script:
    - sh .travis-create-release.sh $TRAVIS_OS_NAME
    - tar -xvzf _srcdist.tar.gz
    - cd _srcdist
    - ./config $CONFIG_OPTS;
    - cd ..

script:
    - cd _srcdist
    - make
    - HARNESS_VERBOSE=yes make test
    - cd ..
