platform:
  - x86
  - x64

configuration:
  - shared
  - static

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLCHAIN_VERSION: 15
    BUILD_TARGERT: windows_msvc

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 12
  
  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 11

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 9

install:
  - for /f "delims=" %%i in ('git describe --tags') do (set BUILD_VERSION=%%i)
  - if "%BUILD_VERSION%" == "" for /f "delims=" %%i in ('git rev-parse HEAD') do (set BUILD_VERSION=%%i) 
  - echo BUILD_VERSION=%BUILD_VERSION%
  - if "%platform%" == "x64" (set varch=amd64) else (set varch=x86)
  - echo "varch:%varch%"
  - if "%BUILD_TARGERT%" == "windows_msvc" if %TOOLCHAIN_VERSION% LSS 15 ( call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch% ) else ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch% )

build_script:
  - C:\msys64\usr\bin\bash.exe -e -l -c "bash /c/projects/openssl/ci/build.sh /c/projects/openssl"

test_script:
