configuration:
  - shared
  - static

platform:
  - 32
  - 64

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLCHAIN_VERSION: 15
    BUILD_TARGERT: windows_msvc

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 12
  
  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 11

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 10
  
  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 9

  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 630
      
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530

install:
  - for /f "delims=" %%i in ('git describe --tags') do (set BUILD_VERSION=%%i)
  - if "%BUILD_VERSION%" == "" for /f "delims=" %%i in ('git rev-parse HEAD') do (set BUILD_VERSION=%%i) 
  - echo BUILD_VERSION=%BUILD_VERSION%
  - if "%platform%" == "64" (set varch=amd64) else (set varch=x86)
  - echo "varch:%varch%"
  - if "%BUILD_TARGERT%" == "windows_msvc" if %TOOLCHAIN_VERSION% LSS 15 ( call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch% ) else ( call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch% )

build_script:
  - C:\msys64\usr\bin\bash.exe -e -l -c "bash /c/projects/openssl/ci/build.sh /c/projects/openssl"

test_script:

artifacts:
  - path: setup
    name: $(BUILD_VERSION)_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(platform)_$(CONFIGURATION)
    type: zip

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master

deploy:
  provider: GitHub
  #token: https://github.com/settings/tokens encode token: https://ci.appveyor.com/tools/encrypt
  auth_token:
    secure:  #TODO: set your token
  on:
    appveyor_repo_tag: true        # deploy on tag push only
