name: GitHub CI

on: [pull_request, push]

# for some reason, this does not work:
# variables:
#   BUILDOPTS: "-j4"
#   HARNESS_JOBS: "${HARNESS_JOBS:-4}"

# for some reason, this does not work:
# before_script:
#     - make="make -s"

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
    - name: install unifdef
      run: |
        echo 'action' ${{ github.action }}
        echo 'name' ${{ github.event_name }}
    - name: more
      if: contains('push', github.event_name)
      run: echo push event
    - name: make build_generated
      if: ${{ !contains('push', github.event_name) }}
      run: echo not push event
    - name: pr1
      if: contains('pull_request', github.event_name)
      run: echo pr1
    - name: pr2
      if: contains(github.event_name, 'pull_request')
      run: echo pr2
