name: GitHub CI

on: [pull_request, push]

# for some reason, this does not work:
# variables:
#   BUILDOPTS: "-j4"
#   HARNESS_JOBS: "${HARNESS_JOBS:-4}"

# for some reason, this does not work:
# before_script:
#     - make="make -s"

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
    - name: install unifdef
      run: |
        echo ${{ github.action }}
        ecco ${{ github.event_name }}
    - name: more
      if: github.event_name == "push"
      run: echo push event
    - name: make build_generated
      if: github.event_name != "push"
      run: echo not push event
