name: Compiler Zoo CI

on: [pull_request, push]

jobs:
  compiler:
    strategy:
      fail-fast: false
      matrix:
        zoo: [
          {
            cc: clang-6.0
          }, {
            cc: clang-7
          }, {
            cc: clang-8
          }, {
            cc: clang-9
          }, {
            cc: clang-10
          }, {
            cc: clang-11
          }, {
            cc: clang-12
          }
        ]
    runs-on: ubuntu-latest
    steps:
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -yq --force-yes install ${{ matrix.zoo.cc }}
        sudo apt-get -yq --force-yes install gcc-multilib
    - uses: actions/checkout@v2

    - name: config
      run: |
        CC=${{ matrix.zoo.cc }} ./config --banner=Configured linux-x86-clang no-shared \
            -Wall enable-fips

    - name: config dump
      run: ./configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: make test
      run: make test HARNESS_JOBS=${HARNESS_JOBS:-4}
