# Copyright 2021-2023 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Compiler Zoo CI

on: [push]

permissions:
  contents: read

jobs:
  compiler:
    strategy:
      fail-fast: false
      matrix:
        zoo: [
          {
            cc: gcc,
            image: "docker.io/library/gcc:7"
          }, {
            cc: gcc,
            image: "docker.io/library/gcc:8"
          }, {
            cc: gcc,
            image: "docker.io/library/gcc:9"
          }, {
            cc: gcc,
            image: "docker.io/library/gcc:10"
          }, {
            cc: gcc,
            image: "docker.io/library/gcc:11"
          }, {
            cc: gcc,
            image: "docker.io/library/gcc:12"
          }, {
            cc: gcc,
            image: "docker.io/library/gcc:13"
          }, {
            cc: clang-8,
            image: "docker.io/tuxmake/clang-8"
          }, {
            cc: clang-9,
            image: "docker.io/tuxmake/clang-9"
          }, {
            cc: clang-10,
            image: "docker.io/tuxmake/clang-10"
          }, {
            cc: clang-11,
            image: "docker.io/tuxmake/clang-11"
          }, {
            cc: clang-12,
            image: "docker.io/tuxmake/clang-12"
          }, {
            cc: clang-13,
            image: "docker.io/tuxmake/clang-13"
          }, {
            cc: clang-14,
            image: "docker.io/tuxmake/clang-14"
          }, {
            cc: clang-15,
            image: "docker.io/tuxmake/clang-15"
          }, {
            cc: clang-16,
            image: "docker.io/tuxmake/clang-16"
          }
        ]
    runs-on: ubuntu-latest
    container: ${{ matrix.zoo.image }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "true"
    - name: config
      run: CC=${{ matrix.zoo.cc }} ./config --banner=Configured no-shared -Wall -Werror enable-fips --strict-warnings
    - name: config dump
      run: ./configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: make test
      run: make test HARNESS_JOBS=${HARNESS_JOBS:-4}
