# Copyright 2023 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Cygwin tests

on: [pull_request, push]

permissions:
  contents: read

jobs:
  cygwin:
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        os:
          - windows-2019
# really worth while running, too? cygwin should mask this
          - windows-2022
        platform:
          - arch: win64
            config: -DCMAKE_C_COMPILER=gcc --strict-warnings no-fips enable-quic
# are we really learning sth new from win32?
          - arch: win32
            config: -DCMAKE_C_COMPILER=gcc --strict-warnings no-fips enable-quic
    runs-on: ${{matrix.os}}
    env:
      CYGWIN_NOWINPATH: 1
      SHELLOPTS: igncr
# Don't overwhelm github CI VMs:
      MAKE_PARAMS: -j 4
    steps:
# Checkout before cygwin can mess with PATH...
    - uses: actions/checkout@v3
    - uses: cygwin/cygwin-install-action@master
      with:
         packages: perl git make gcc-core
    - name: Check repo
      run: cygcheck -V
    - name: Full cygcheck status
      run: cygcheck -s -v -r -h 
# Activate this if checkout action fails:
#    - name: Clone repo 
#      run: bash -c "pwd && git clone --branch ${{ github.ref_name }} --depth 1 https://github.com/${{ github.repository }}.git"
    - name: Full build
      run: bash -c "pwd && ls && ./config ${{ matrix.platform.config }} && make $MAKE_PARAMS"
# Disable testing for now. TBD: Need local cygwin installation to debug .
#    - name: Run openssl tests
#      run: bash -c "cd openssl && make V=1 test"

