# Copyright 2021 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: OS Zoo CI

on: [push]

permissions:
  contents: read

jobs:
  unix:
    strategy:
      fail-fast: false
      matrix:
        os: [
          macos-10.15,
          macos-11,
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        CC=${{ matrix.zoo.cc }} ./config --banner=Configured
    - name: config dump
      run: ./configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: make test 1
      run: ./test/threadstest
    - name: make test 2
      run: ./test/threadstest
    - name: make test 3
      run: ./test/threadstest
    - name: make test 4
      run: ./test/threadstest
    - name: make test 5
      run: ./test/threadstest
    - name: make test 6
      run: ./test/threadstest
    - name: make test 7
      run: ./test/threadstest
    - name: make test 8
      run: ./test/threadstest
    - name: make test 9
      run: ./test/threadstest
    - name: make test 10
      run: ./test/threadstest
