# Copyright 2022 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Provider compatibility across versions
on:
  schedule:
    - cron: '0 7 * * *'

permissions:
  contents: read

env:
  opts: enable-rc5 enable-md2 enable-ssl3 enable-weak-ssl-ciphers enable-zlib

jobs:
  provider-compatibility:
    strategy:
      matrix:
        tag: [
          openssl-3.0.0,
          openssl-3.0.1,
          openssl-3.0.2,
          openssl-3.0.3,
          openssl-3.0.4,
          openssl-3.0.5,
        ]
    runs-on: ubuntu-latest
    steps:
      - name: create directories
        run: |
            mkdir ./current
            mkdir ./old
      - uses: actions/checkout@v2
        with:
          path: current
      - uses: actions/checkout@v2
        with:
          repository: openssl/openssl
          ref: ${{ matrix.tag }}
          path: old
      - name: localegen
        run: sudo locale-gen tr_TR.UTF-8
      - name: config current
        run: |
          ./config --banner=Configured enable-shared enable-fips ${{ env.opts }}
        working-directory: ./current
      - name: config dump current
        run: ./configdata.pm --dump
        working-directory: ./current
      - name: make current
        run: make -s -j4
        working-directory: ./current
      - name: test current
        run: make test HARNESS_JOBS=${HARNESS_JOBS:-4}
        working-directory: ./current

      - name: config module
        run: |
          ./config --banner=Configured enable-shared enable-fips ${{ env.opts }}
        working-directory: old
      - name: config dump module
        run: ./configdata.pm --dump
        working-directory: old
      - name: make module
        run: make -s -j4
        working-directory: old

      - name: show modules from current
        run: |
          ./util/wrap.pl -fips apps/openssl list -provider-path providers \
                                                 -provider base \
                                                 -provider default \
                                                 -provider fips \
                                                 -provider legacy \
                                                 -providers
        working-directory: ./current
      - name: setup module cross validation
        run: |
            cp providers/fipsmodule.cnf ../current/providers/
            cp providers/*.so ../current/providers/
        working-directory: old
      - name: show old modules
        run: |
          ./util/wrap.pl -fips apps/openssl list -provider-path providers \
                                                 -provider base \
                                                 -provider default \
                                                 -provider fips \
                                                 -provider legacy \
                                                 -providers
        working-directory: ./current
      - name: test module cross validation
        run: make test HARNESS_JOBS=${HARNESS_JOBS:-4}
        working-directory: ./current
