name: Windows GitHub CI

on: [pull_request, push]

jobs:
  minimal:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: configbuildandtest
      env:
        CONFIG_OPTS: no-bulk no-deprecated no-fips no-asm -DOPENSSL_SMALL_FOOTPRINT
        TARGET: VC-WIN64A
      run: |
        mkdir _build
        cd _build
        perl ..\Configure $TARGET no-makedepend $CONFIG_OPTS
