# Copyright 2021-2024 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Build Windows Installer

on:
  workflow-dispatch:
    inputs:
      tag:
        type: string
        description: The tag to build

permissions:
  contents: read

jobs:
  runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.tag }}
    - name: Setup Build dir
      run: |
        mkdir _build
    - name: download NSIS installer
      uses: suisei-cn/actions-download-file@v1.6.0
      with:
        url: "https://downloads.sourceforge.net/project/nsis/NSIS%203/3.08/nsis-3.08-setup.exe"
        target: _build/
    - name: Install NSIS 3.0
      run: |
        _build\nsis-3.0.8-setup.exe /S 
        del _build\nsis-3.0.8-setup.exe
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win64
    - uses: ilammy/setup-nasm@v1
      with:
        platform: win64
    - name: config
      working-directory: _build
      run: |
        perl ..\Configure --banner=Configured no-makedepend enable-fips
        perl configdata.pm --dump
    - name: build x64 binaries
      working-directory: _build
      run: nmake /S


