# Copyright 2021-2023 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Wrangler Triage Actions 

on:
  workflow_dispatch:
    inputs:
      severity:
        description: Issue Severity
        required: true
        type: choice
        options:
        - low
        - medium
        - high
        - immediate
      category:
        description: Issue Type
        required: true
        type: choice
        options:
        - bug
        - feature
        - documentation
        - performance
        - cleanup

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

env:
  GH_TOKEN: ${{ secrets.github_token }}

jobs:
  do_triage:
  runs_on: ubuntu-latest
  steps:
    - run: |
      echo "selected severity: ${{ inputs.severity }}"
      echo "selected category: ${{ inputs.category }}"
